### ISSUE TITLE
#4. Fix on Work orders: The supplier item on an existing work order is not editable.

### ISSUE THREAD

**Issue by ananya-rajput** [dailykit/dailyos#108]
Once a work is created, the supplier item as well as the input item selected for the work order will not be editable anymore.
This will lead to issues: For example right now, if on a bulk work order, if the user changes the supplier item, and updates the work order. That leads to problem with output bulk item as both the input and output items should belong to one supplier item.

On clicking on edit, the editable fields of a work order are: 1. output item, 2. yield, 3. lebal, 4. user assigned, 5. scheduled on.

**Comment by siddhantk232** [comment]
Thanks for reporting this issue @ananya-rajput. This has been fixed and the changes are in the staging branch right now :)
