### ISSUE TITLE
#2. Fix on supplier item form: The button NEXT on tunnel item name and quantity is not working

### ISSUE THREAD

**Issue by ananya-rajput** [dailykit/dailyos#112]
1. Fix the button next on the tunnel.
2. Add action to edit on the meta information like Unit quantity, case quantity.
3. Fix the button same on tunnel Configure Processing

**Comment by siddhantk232** [comment]
Thanks for creating this issue @ananya-rajput This now has been fixed and is under review in the `staging` branch :)
