### ISSUE TITLE
Adding ingredient sachet throws foreign key violation

### ISSUE THREAD

**Issue by prvnbist** [dailykit/dailyos#159]
Error:
```
Error: "GraphQL error: Foreign key violation. insert or update on table "ingredientSachet" violates foreign key constraint "ingredientSachet_unit_fkey""
```

Steps to reproduce:
1. Create Ingredient
2. Create Processing
3. Add Sachet
3.1 Keep selection to `Bar` i.e default value selection causes this error
4. Try to save sachet

**Comment by welcometodailykit** [comment]
@thesanjeevsharma is it taken care of?
