### ISSUE TITLE
Setting App-> Master lists -> Accompaniment types -> Leads to a blank page

### ISSUE THREAD

**Issue by ambikantpc1987** [dailykit/dailyos#241]
**Steps to Reproduce**
1) Click on the setting app.
2) Now click on master list
3) Now click on Accompaniment types.

**Actual result**
1) When clicking on Accompaniment types it leads to a blank screen.

**Expected result**
1) It should show a page where the user can add.

![Accompaniment types_blank screen](https://user-images.githubusercontent.com/43462145/92443213-ce9a5800-f1ce-11ea-9ad4-c2589f5d0f9e.PNG)

**Comment by prvnbist** [comment]
Could not reproduced, closing for now.
