### ISSUE TITLE
Setting app-> Users-> No edit option once it published

### ISSUE THREAD

**Issue by ambikantpc1987** [dailykit/dailyos#274]
**Steps to reproduce**
1) Go to setting app
2) Now click on Users.
3) Enter all the details and click on publish.
4) Now try to edit something

**Expected result**
1) There should be an edit option for users added

**Actual result**
1) There is no edit option.

![user_no edit](https://user-images.githubusercontent.com/43462145/93330101-e52e5800-f83b-11ea-88d7-996955b7ff11.PNG)

**Comment by prvnbist** [comment]
The details entered for the user here goes into creating the user in Keycloak, this feature won't likely be added anytime soon. We'll reopen this issue once we start work on this.

Thanks for mentioning the issue.

**Comment by prvnbist** [comment]
Fixed in PR #282
