### ISSUE TITLE
Setting app-> Users->Blank user is able to publish

### ISSUE THREAD

**Issue by ambikantpc1987** [dailykit/dailyos#275]
**Steps to reproduce**
1) Go to the setting app.
2) Now click on Users
3) Now enter the special character (Space) in all field and click on the publish button

**Expected Result**
1) Only space should not be allowed in any field

**Actual result**
1) User is able to enter space and can publish a 
![blank_user_added](https://user-images.githubusercontent.com/43462145/93330762-e9a74080-f83c-11ea-8cd6-a256c5bf2a9a.PNG)
blank row.

**Comment by prvnbist** [comment]
Fixed
