### ISSUE TITLE
Setting app-> Stations->Add user leads to a blank page

### ISSUE THREAD

**Issue by ambikantpc1987** [dailykit/dailyos#276]
**Steps to Reproduce**
1) Go to setting app
2) Now click on Stations
3) Now click on the (+) sign and click on "Add User" button

**Expected Result**
1) It should able to add the user while clicking on the add user button

**Actual Result**
1) While clicking on add user button it leads to a blank screen

![station_adduser-blankpage](https://user-images.githubusercontent.com/43462145/93332256-3429bc80-f83f-11ea-82e6-283626c2e6ae.PNG)

**Comment by prvnbist** [comment]
Seems like there was a User without first/last name, that caused to to crash. I'll put strict validation in User form to avoid this in future and also update the Component that caused the crash.
