### ISSUE TITLE
Setting app-> Stations-> Role-> The page becomes unresponsive

### ISSUE THREAD

**Issue by ambikantpc1987** [dailykit/dailyos#278]
Steps to reproduce
1) Go to setting app.
2) Now click on the station.
3) Now from the sidebar menu click on Role and click the (+) sign

Expected result
1) It should open the page to add the role

Actual result
The page becomes unresponsive. 

![role-page unresponsive](https://user-images.githubusercontent.com/43462145/93457178-533a5400-f8fc-11ea-8da6-0eb82cea7b68.PNG)

**Comment by prvnbist** [comment]
Adding the new role feature is not there anymore let's close this for now and reopen once we add the feature back again.

Thanks for mentioning this.
