### ISSUE TITLE
Setting App-> Stations-> Publish button is not clickable to publish the station name.

### ISSUE THREAD

**Issue by ambikantpc1987** [dailykit/dailyos#292]
**Steps to reproduce**
1) Go to setting app. Click on Stations
2) Now click on the sign (+) and click on add user
3) Select the user and click on the Save button.
4) Now click on the publish button

**Expected result**
1) User name should be published

**Actual result**
1) Publish button is not clickable

![settingapp_publish](https://user-images.githubusercontent.com/43462145/94122772-96527500-fe70-11ea-8d1c-c75926d3fdd3.PNG)
.

**Comment by prvnbist** [comment]
Publish button is only for saving the name of the station, users, printers saved as soon as they are added. I'll work the station form to make this clear as well.
