### ISSUE TITLE
Tabulator default table, and column sizes

### ISSUE THREAD

**Issue by welcometodailykit** [dailykit/dailyos#335]
Currently, since the column sizes and other things aren't configured, the default render of react-tabulator is weird and not appropriate to the relevant column.

We need to define pagination, a standard width, height of the tabulator component and at the same time make it clean looking.

1. The column names should be in center of the column as opposed to left-aligned
2. Improve the styling of table header with column names and all..

**Comment by prvnbist** [comment]
Column name alignment depends on the type of content it will have, for ex.
for actions, it should be in center along with content
for numbers, it should be right aligned along with content
for simple text, it should be left aligned along with content
