### ISSUE TITLE
Recipe form: sachet visibility is not functioning

### ISSUE THREAD

**Issue by ananya-rajput** [dailykit/dailyos#559]
The toggle for visibility on each serving sachet is not functioning. @thesanjeevsharma 
![image](https://user-images.githubusercontent.com/59871793/114359939-1a144a80-9b92-11eb-8c26-c1929ffc0201.png)

**Comment by thesanjeevsharma** [comment]
@ananya-rajput closing this, as this is an issue in the UI-lib component and not the recipe form.
