### ISSUE TITLE
Add toggle on Ingredient visibility.

### ISSUE THREAD

**Issue by ananya-rajput** [dailykit/dailyos#88]
The ingredient visibility is an action similar to step visibility.
Make the ingredient visibility as toggle and enabled by default.
![image](https://user-images.githubusercontent.com/59871793/82216655-e5beec80-9936-11ea-8d25-13d27a7fd370.png)

**Comment by thesanjeevsharma** [comment]
This was done on purpose! It's better if updates happen through the tunnel. With tunnel, users will know if the update was done or not.
Here it's hard to debounce multiple clicks. And if the internet is slow, they'll never know if the update was done or not.
